### ISSUE TITLE
document users_file

### ISSUE THREAD

**Issue by jampy** [rlidwka/sinopia#148]
In the default config.yaml file there is this comment:

```
# a list of users
#
# This could be deprecated soon, use "users_file" instead.
users:
  admin:
    # crypto.createHash('sha1').update(pass).digest('hex')
    password: xxx
```

However, I can't find information about `users_file` to set up my installation..
