### ISSUE TITLE
How to administrate a sinopia server (private npm registry)?

### ISSUE THREAD

**Issue by rbecheras** [rlidwka/sinopia#291]
Hi! guys !

First of all, @rlidwka : thanks for this awesome application ! I love it!

Now, my feedback/issue:

I can't get what are the administration features..

- is there admin features ?
- can a system admin create a sinopia admin account or the admin features must be run by system admin over ssh ?
- how system admin can create a sinopia admin account ?
- how an admin can control other user registrations, or team membership?
- how an admin can access email  of users (in order to send email notifications for example)

Thanks in advance for your help.
Rémi.

**Comment by blittle** [comment]
:+1:

**Comment by rlidwka** [comment]
There are no special admin account. Everything an admin is supposed to do should be possible to do by editing a config file.

> how an admin can control other user registrations, or team membership?

You can enable/disable user registration in a [config file](https://github.com/rlidwka/sinopia/blob/6b3617754c7bac6ad08366046be87361bb8a6b24/conf/default.yaml#L12-L17):

```yaml
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 0 # this will do the trick
```

I usually keep it disabled and enable temporarily when new developer is accepted to the company. But registration doesn't give users any additional power, so you could just keep it open.

About team membership, there are no teams, there are just lists of users. You can emulate teams with yaml repeated nodes however:

```yaml
some_irrelevant_key_here: &team1 [ user1, user2, user3 ]
some_irrelevant_key_here: &team2 [ user4, user5 ]

packages:
  foo:
    access: [ &team1, &team2 ]
    publish: &team1
```

You can check how it's parsed [here](https://nodeca.github.io/js-yaml/).

Sinopia doesn't have teams, but such YAML syntax allows you to avoid repeating the same user list over and over again.

> how an admin can access email of users (in order to send email notifications for example)

Unfortunately, emails are never recorded. I didn't think they would be of any use. If you think they should be, please open a feature request.

Sorry for the delay in answering, too busy with some other projects.
