### ISSUE TITLE
one of the uplinks is down, refuse to publish?

### ISSUE THREAD

**Issue by ghost** [rlidwka/sinopia#356]
I have successfully installed sinopia on docker engine. But failed to publish my first package into it.
Below is the error statcktrace

[root@xxxxxx ibm-c3]# npm publish
npm ERR! publish Failed PUT 503
npm ERR! Linux 3.10.0-229.4.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code E503

npm ERR! one of the uplinks is down, refuse to publish : ibm-c3
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/xuhang/ibm-c3/npm-debug.log

I have already viewed the related topic about this issue like below two, but did not help me. 
https://github.com/rlidwka/sinopia/issues/289
https://github.com/rlidwka/sinopia/issues/124

Any one can help me? thanks.

**Comment by MickelSierra85** [comment]
Hi, 
do you have internet access?

Can you publish your configuration?

**Comment by yinrong** [comment]
+1

**Comment by jennasalau** [comment]
Hi,

I was having this issue and **resolved** it by setting my companies proxy information on the sinopia server.

Make sure your server can access the **uplink** urls set in `config.yaml` 

For me since my server is behind a proxy i needed to add the proxy deets.

example _in config.yaml_

```
# Proxy for uplinks
http_proxy: http://user:pass@myproxy.com:80
https_proxy: http://user:pass@myproxy.com:80

# a list of other known repositories we can talk to
uplinks:
    npmjs:
         url: https://registry.npmjs.org/
```
