### ISSUE TITLE
[Help] Failed to install scoped package @reactivex/rxjs

### ISSUE THREAD

**Issue by lanfeng** [rlidwka/sinopia#388]
I noticed that it was an issue to install scoped package and there is already some fix committed in master branch. So I install the Sinopia@1.4.0, fetch the latest master code to merge and replace Sinopia install folder. However it still failed to install scoped package.

So I am wondering,
1) Does Sinopia Master branch support to install scoped packages now? 
2) If it does support, what did I wrong.
3) how to build the master branch locally in my computer.

Thanks for your input.

Regards,

Lanfeng

**Comment by lanfeng** [comment]
@rlidwka

**Comment by mstorus** [comment]
@lanfeng do you have a proxy specified for both scoped and non-scoped packages in your config.yaml?
example:

```
packages:
  '*':
    access: $all
    publish: $all
    proxy: npmjs

  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
```
