### ISSUE TITLE
Users config is currently silly

### ISSUE THREAD

**Issue by josephg** [rlidwka/sinopia#68]
This seems silly:

``` yaml
users:
  josephg:
    password: xxx
  ishbu:
    password: xxx
  enjalot:
    password: xxx
  nateps:
    password: xxx

packages:
  'someprefix-*':
    # allow all users to read packages ('all' is a keyword)
    # this includes non-authenticated users
    allow_access:
      - josephg
      - ishbu
      - nateps
      - enjalot
    # allow 'admin' to publish packages
    allow_publish:
      - josephg
      - ishbu
      - nateps
      - enjalot
```

There should be a keyword like `all` which is a wildcard for all registered users, or enable groups (so I can put all my users in a group and reference the group in allow_access).
